name: CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: deploy
        name: Deploy to dokku
        run: |
          git remote add dokku dokku@recipe.nycplanningdigital.com:recipe
          git push dokku master